config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import (HomePageView, RegisterView, LoginView, CourseDetailView,
                    AddCourseView, UpdateCourseView, ServiceView, ServiceDetailView)

app_name = 'main'

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
    path('register', RegisterView.as_view(), name="register"),
    path('login', LoginView.as_view(), name="kirish"),
    path('course/<str:slug>', CourseDetailView.as_view(), name="detail"),
    path('add_course', AddCourseView.as_view(), name="add_course"),
    path('course/<int:pk>/edit', UpdateCourseView.as_view(), name="update_course"),
    path('service/', ServiceView.as_view(), name="services"),
    path('service_detail/', ServiceDetailView.as_view(), name='service-detail'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, User
from django.urls import reverse
from django.core.validators import FileExtensionValidator
from PIL import Image
from django.db import models



# Create your models here.

class User(AbstractUser):
    phone = models.CharField(max_length=13, blank=True, unique=True, db_index=True)
    auth_code = models.CharField(max_length=6, blank=True)

    # def get_absolute_url(self):
    #     print(self)
    #     return reverse("main:account", kwargs={"id": self.id})

    def __str__(self) -> str:
        return f"{self.username}"


class Category(models.Model):
    title = models.CharField(max_length=15)

    def __str__(self) -> str:
        return f"{self.title}"


class Tag(models.Model):
    title = models.CharField(max_length=15)

    def __str__(self) -> str:
        return f"{self.title}"




class Course(models.Model):
    LANGUAGES = (
        ('uz', 'O\'zbekcha'),
        ('ru', 'Ruscha'),
        ('en', 'Inglizcha'),
    )
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=255, unique=True, blank=True)
    description = models.TextField()
    duration = models.DurationField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)  # 100.00
    category = models.ForeignKey('Category', on_delete=models.CASCADE, related_name="courses")
    created_at = models.DateTimeField(verbose_name="Boshlanish vaqti")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Yangilanish vaqti")
    language = models.CharField(max_length=100, blank=True, choices=LANGUAGES)
    rating = models.PositiveBigIntegerField(verbose_name="Rating", default=0)
    image = models.ImageField(upload_to="images", blank=True)
    tags = models.ManyToManyField('Tag', verbose_name="tags")

    class Meta:
        ordering = ['-rating']

    def save(self, *args, **kwargs):
        # Call the parent save method to save the object
        super().save(*args, **kwargs)

        if self.image:
            img = Image.open(self.image.path)

            # Resize the image to 150x220
            img = img.resize((150, 220), Image.ANTIALIAS)
            img.save(self.image.path)


# -------------------------------------------------------------------

class Header(models.Model):
    message = models.CharField(max_length=150)
    facebook = models.CharField(max_length=30)
    twitter = models.CharField(max_length=30)
    youtube = models.CharField(max_length=30)
    linkedin = models.CharField(max_length=30)
    logo = models.ImageField(upload_to="header/logo/")
    address = models.CharField(max_length=150)
    phone1 = models.CharField(max_length=15)
    phone2 = models.CharField(max_length=15)
    email1 = models.EmailField()
    email2 = models.EmailField()

    def __str__(self):
        return f"{self.message}"


class HeaderImage(models.Model):
    service = models.CharField(max_length=100)
    content = models.CharField(max_length=255)
    header = models.ForeignKey(Header, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='header/images/')


class Service(models.Model):
    title = models.CharField(max_length=150)
    content = models.TextField()
    image = models.ImageField(upload_to="service/", help_text="O'lcham: 371x202 px")
    book_image = models.ImageField(upload_to="book/image/", help_text="O'lcham 160x250 px")


class ServiceBook(models.Model):
    service = models.ForeignKey(Service, on_delete=models.PROTECT)
    file = models.FileField(upload_to="book/file/", validators=[
        FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])
    ])

templates/base.html
<!DOCTYPE html>
<!-- 
Template Name: Edu365 Education HTML
Version: 1.0.0
Author: Webstrot

-->
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="zxx">
<!--[endif]-->

<head>
    <meta charset="utf-8" />
    <title>Edu365 Education HTML Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta name="description" content="Education" />
    <meta name="keywords" content="Education" />
    <meta name="author" content="" />
    <meta name="MobileOptimized" content="320" />
    <!--Template style -->
    {% include 'components/_style.html' %}

</head>

<body>
        <div id="preloader">
        <div id="status">
            <img src="/static/images/preloader.gif" id="preloader_image" alt="loader">
        </div>
    </div>
    <!-- edu top header wrapper Start -->
        {% include 'components/header/_top_header.html' %}
    <!-- edu top header wrapper End -->

    <!-- edu logo header wrapper Start -->
        {% include 'components/header/_logo_header.html' %}
    <!-- edu logo header wrapper End -->

    <!-- edu navihation header wrapper Start -->
        {% include 'components/header/_navihation_header.html' %}
    <!-- edu navihation header wrapper End -->

        <!-- edu slider wrapper Start -->
        {% block slider %}
        {% include 'components/header/_slider.html' %}
        {% endblock slider %}
    <!-- edu slider wrapper End -->

    {% block content %}
    {% endblock content %}

     <!-- footer Wrapper Start -->
    {% include 'components/_footer.html' %}
    <!-- footer Wrapper End -->

    {% include 'components/_script.html' %}

</body>
</html>

templates/course_add.html
{% extends 'page_wrapper.html' %}
{% block page %}
	<!-- inner header wrapper start -->
	<div class="page_title_section float_left">
		<div class="page_header">
			<div class="container">
				<div class="row">
					<!-- section_heading start -->
					<div class="col-lg-12 col-md-12 col-12 col-sm-12">
						<h1>Course single</h1>
					</div>
					<div class="col-lg-12 col-md-12 col-12 col-sm-12">
						<div class="sub_title_section">
							<ul class="sub_title">
								<li> <a href="#"> Home </a> &nbsp;&nbsp;&nbsp; &gt; &nbsp;&nbsp;</li>
								<li>Course single</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- inner header wrapper end -->
	<!--blog wrapper start-->
	<div class="blog_wrapper float_left">
		<div class="container">
			<div class="row">
				<div class="col-xl-8 col-lg-8 col-md-12 col-sm-12 col-xs-12">

                    <form action="" method="post" enctype="multipart/form-data">
                       {% csrf_token %}

                     {% if form.errors %}  
                        {% for error in  form.errors %}
                            <h1>{{ error }}</h1>
                        {% endfor %}  
                     {% endif %}  

                       
                     {% for field in form %}
                        <div class="form-group">
                            <label for="">{{ field.label }}</label>
                            {{ field }}
                        </div>
                     {% endfor %} 
                     
                     <div class="form-group">
                        <button class="btn btn-success" type="submit"> {{ button }} </button>
                     </div>

                       
                    </form>

               </div>     
            </div>     
        </div>     
    </div>     
{% endblock page %}

templates/course_single.html
{% extends 'page_wrapper.html' %}
{% block page %}

<!-- inner header wrapper start -->
<div class="page_title_section float_left">
    <div class="page_header">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-12 col-sm-12">
                    <h1>Course single</h1>
                </div>
                <div class="col-lg-12 col-md-12 col-12 col-sm-12">
                    <div class="sub_title_section">
                        <ul class="sub_title">
                            <li> <a href="/"> Home </a> &nbsp;&nbsp;&nbsp; &gt; &nbsp;&nbsp;</li>
                            <li>Course single</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- inner header wrapper end -->

<!--blog wrapper start-->
<div class="blog_wrapper float_left">
    <div class="container">
        <div class="row">
            <div class="col-xl-8 col-lg-8 col-md-12 col-sm-12 col-xs-12">
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Course Detail</title>
                <style>
                    .course-thumbnail img {
                        width: 150px;
                        height: 220px;
                        object-fit: cover;
                    }

                    .course-detail {
                        display: flex;
                        align-items: flex-start;
                        margin-bottom: 20px;
                    }

                    .course-info {
                        margin-left: 20px;
                    }

                    .course-info h1 {
                        font-size: 24px;
                        margin-bottom: 10px;
                    }

                    .course-info p {
                        margin-bottom: 8px;
                    }
                </style>

                <div class="course-detail">
                    <div class="course-thumbnail">
                        <img src="{{ course.image.url }}" alt="{{ course.title }}">
                    </div>
                    <div class="course-info">
                        <h1>{{ course.title }}</h1>
                        <p><strong>Category:</strong> {{ course.category.title }}</p>
                        <p><strong>Start Date:</strong> {{ course.created_at|date:"F j, Y" }}</p>
                        <p><strong>Duration:</strong> {{ course.duration }}</p>
                        <p><strong>Language:</strong> {{ course.get_language_display }}</p>
                        <p><strong>Price:</strong> ${{ course.price }}</p>
                        <p><strong>Rating:</strong> {{ course.rating }} stars</p>
                        <p>{{ course.description }}</p>
                    </div>
                </div>

                <div class="tb_btm_link_left">
                    <ul>
                        <li><span><i class="fa fa-tag"></i> Tags :</span></li>
                        {% for tag in course.tags.all %}
                        <li><a href="#">{{ tag }}</a></li>
                        {% endfor %}
                    </ul>
                </div>

                <!-- Comments Section -->
                <div class="comments_wrapper float_left">
                    <div class="widget_heading">
                        <h2>comments ({{ course.comments.count }})</h2>
                    </div>
                    <div class="row">
                        {% for comment in course.comments.all %}
                        <div class="col-lg-12 col-md-12 col-12 col-sm-12">
                            <div class="comments_Box">
                                <div class="img_wrapper">
                                    <img src="{{ comment.user.profile_image.url }}" class="" alt="author_img" />
                                </div>
                                <div class="text_wrapper">
                                    <div class="author_detail">
                                        <span class="author_name">{{ comment.user.username }} <i class="fa fa-circle"></i></span>
                                        <span class="publish_date">{{ comment.created_at|date:"F j, Y" }} - <a href="#">Reply</a></span>
                                    </div>
                                    <div class="author_content">
                                        <p>{{ comment.content }}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>

                <!-- Leave a Comment Section -->
                <div class="comments_form float_left">
                    <div class="widget_heading">
                        <h2>leave a comment</h2>
                    </div>
                    <form method="POST" action="/add_comment">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6 col-sm-12">
                                <div class="formsix-pos">
                                    <div class="form-group i-name">
                                        <label class="sr-only">Name</label>
                                        <input type="text" name="name" class="form-control" required="" placeholder="Full Name *">
                                        <i class="fas fa-user-alt"></i>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 col-sm-12">
                                <div class="formsix-e">
                                    <div class="form-group i-email">
                                        <label class="sr-only">Email</label>
                                        <input type="email" name="email" class="form-control" required="" placeholder="Email Address *">
                                        <i class="fas fa-envelope"></i>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12 col-sm-12">
                                <div class="formsix-m">
                                    <div class="form-group i-message">
                                        <label class="sr-only">Message</label>
                                        <textarea class="form-control" name="message" required="" rows="4" placeholder="Message"></textarea>
                                        <i class="fas fa-comment"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="edu_bottom_btn_wrapper edu_btn float_left">
                            <button type="submit" class="btn">Send Now</button>
                        </div>
                    </form>
                </div>
            </div>

            <!-- Sidebar -->
            <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-xs-12 right_sidebar blog_single_sidebar">
                <!-- Social Share -->
                <div class="tb_btm_link_right">
                    <ul>
                        <li>share :</li>
                        <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                        <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
                    </ul>
                </div>

                <!-- Search Widget -->
                <div class="sidebar_widget float_left">
                    <div class="widget_heading">
                        <h2>Search feed</h2>
                    </div>
                    <form class="search_form" role="search">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Search...">
                        </div>
                        <button type="submit"><i class="fa fa-search"></i></button>
                    </form>
                </div>

                <!-- Latest Posts -->
                <div class="sidebar_widget float_left">
                    <div class="widget_heading">
                        <h2>Latest post</h2>
                    </div>
                    <div class="blog_wrapper22 float_left">
                        <div class="blog_image">
                            <img src="images/blog1.jpg" class="img-responsive" alt="blog_img1" />
                        </div>
                        <div class="blog_text">
                            <h5><a href="#">How to Become Master In CSS within a Week.</a></h5>
                            <div class="blog_date">June 28, 2018-19</div>
                        </div>
                    </div>
                    <!-- Repeat similar blocks for other latest posts -->
                </div>

                <!-- Tag Cloud -->
                <div class="sidebar_widget float_left">
                    <div class="widget_heading">
                        <h2>Tags cloud</h2>
                    </div>
                    <div class="sidebar_tag_cloud">
                        <ul>
                            {% for tag in tags %}
                            <li><a href="#">{{ tag }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/register.html
{% extends 'page_wrapper.html' %}
    {% block page %}


	<!-- jp login wrapper start -->
	<div class="login_section">
		<!-- login_form_wrapper -->
		<div class="login_form_wrapper">
			<div class="container">
				<div class="row">
					<div class="col-md-8 offset-md-2">
						<!-- login_wrapper -->
						{{ request.user }}
						<h1>Register TO YOUR <a href="{{ request.user.get_absolute_url }}">ACCOUNT cc</a></h1>
						<div class="login_wrapper">
							<div class="row">
								<div class="col-lg-6 col-md-6 col-xs-12 col-sm-6">
									<a href="#" class="btn btn-primary"> <span>Login with Facebook</span>  <i class="fab fa-facebook-f"></i> 
									</a>
								</div>
								<div class="col-lg-6 col-md-6 col-xs-12 col-sm-6">	<a href="#" class="btn btn-primary google-plus"> Login  with Google <i class="fab fa-google-plus-g"></i></a>
								</div>
							</div>
							<h2>or</h2>
							{% if messages %}
								{% for message in  messages %}
									<h3	class="text-{{ message.tags }}"> {{ message }} </h3>
								{% endfor %}	
							{% endif %}	

						<form action="" method="post" id="form">  
							{% csrf_token %}
							<div class="formsix-pos">
								<div class="form-group">
									<input type="text" name="username" class="form-control" required id="email2" placeholder="Username*">
								</div>
							</div>
							<div class="formsix-e">
								<div class="form-group">
									<input type="email" name="email"  class="form-control" required id="password2" placeholder="Email">
								</div>
							</div>
							<div class="formsix-e">
								<div class="form-group">
									<input type="password" name="password" class="form-control" required="" id="password2" placeholder="Password *">
								</div>
							</div>
							<div class="formsix-e">
								<div class="form-group">
									<input type="password" name="password_confirm" class="form-control" required="" id="password2" placeholder="Re-enter Password *">
								</div>
							</div>
							<div class="formsix-pos">
								<div class="form-group">
									<input type="text" name="phone" class="form-control" required="" id="email2" placeholder="Phone*">
								</div>
							</div>
							<div class="login_remember_box">
								<label class="control control--checkbox">I agreed to the Terms and Conditions.
									<input type="checkbox">	<span class="control__indicator"></span>
								</label>
							</div>
								<div class="login_btn_wrapper">	<button type="submit" href="#" class="btn btn-primary login_btn"> Register Now </button>
							</div>
						</form>
							<div class="login_message">
								<p>Don’t have an account ? <a href="login.html"> LogIn </a> 
								</p>
							</div>
						</div>
						<p>In case you are using a public/shared computer we recommend that you logout to prevent any un-authorized access to your account</p>
						<!-- /.login_wrapper-->
					</div>
				</div>
			</div>
		</div>
		<!-- /.login_form_wrapper-->
	</div>
	<!-- jp login wrapper end -->
	<!--edu letter wrapper Start-->
	<div class="edu_letter_main_wrapper float_left">
		<div class="container">
			<div class="edu_left_envo">
				<img src="/static/images/innn.png" alt="img">
				<h3>Sign up for Newsletter</h3>
			</div>
			<div class="edu_right_form">
				<input type="text" placeholder="Enter your email">
				<button>Sign Up</button>
			</div>
		</div>
	</div>

    {% endblock  %}